[build]
  functions = "netlify/functions"
  publish = "."

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/kentech-session-server"
  status = 200

[[redirects]]
  from = "/*"
  to = "/kentech-session-generator.html"
  status = 200
